apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 3050
      protocol: TCP
      targetPort: 3000
      nodePort: 31050
  type: NodePort
